---
# handlers file for neo4j

- name: Restart Neo4j
  service: name=neo4j state=restarted
  become: true
  become_method: sudo
  when: not (omit_neo_restart is defined and omit_neo_restart == "true")
